isa_sim_args:
  - --prof_pc_start 80000000
  - -t
  - --bp2 global
  - --no_callstack
  - -l

workloads:
  - sw/arch-tests/riscv-arch-test/work/ama-riscv-rv32im/elfs/rv32i/I/I-lbu-00.elf
  - sw/arch-tests/riscv-arch-test/work/ama-riscv-rv32im/elfs/rv32i/I/I-lh-00.elf
  - sw/arch-tests/riscv-arch-test/work/ama-riscv-rv32im/elfs/rv32i/I/I-bgeu-00.elf
  - sw/arch-tests/riscv-arch-test/work/ama-riscv-rv32im/elfs/rv32i/I/I-and-00.elf
  - sw/arch-tests/riscv-arch-test/work/ama-riscv-rv32im/elfs/rv32i/I/I-lw-00.elf
  - sw/arch-tests/riscv-arch-test/work/ama-riscv-rv32im/elfs/rv32i/I/I-andi-00.elf
  - sw/arch-tests/riscv-arch-test/work/ama-riscv-rv32im/elfs/rv32i/I/I-bne-00.elf
  - sw/arch-tests/riscv-arch-test/work/ama-riscv-rv32im/elfs/rv32i/I/I-lui-00.elf
  - sw/arch-tests/riscv-arch-test/work/ama-riscv-rv32im/elfs/rv32i/I/I-sw-00.elf
  - sw/arch-tests/riscv-arch-test/work/ama-riscv-rv32im/elfs/rv32i/I/I-jalr-00.elf
  - sw/arch-tests/riscv-arch-test/work/ama-riscv-rv32im/elfs/rv32i/I/I-srai-00.elf
  - sw/arch-tests/riscv-arch-test/work/ama-riscv-rv32im/elfs/rv32i/I/I-bge-00.elf
  - sw/arch-tests/riscv-arch-test/work/ama-riscv-rv32im/elfs/rv32i/I/I-jal-00.elf
  - sw/arch-tests/riscv-arch-test/work/ama-riscv-rv32im/elfs/rv32i/I/I-slli-00.elf
  - sw/arch-tests/riscv-arch-test/work/ama-riscv-rv32im/elfs/rv32i/I/I-sll-00.elf
  - sw/arch-tests/riscv-arch-test/work/ama-riscv-rv32im/elfs/rv32i/I/I-nop-00.elf
  - sw/arch-tests/riscv-arch-test/work/ama-riscv-rv32im/elfs/rv32i/I/I-lhu-00.elf
  - sw/arch-tests/riscv-arch-test/work/ama-riscv-rv32im/elfs/rv32i/I/I-sub-00.elf
  - sw/arch-tests/riscv-arch-test/work/ama-riscv-rv32im/elfs/rv32i/I/I-xori-00.elf
  - sw/arch-tests/riscv-arch-test/work/ama-riscv-rv32im/elfs/rv32i/I/I-blt-00.elf
  - sw/arch-tests/riscv-arch-test/work/ama-riscv-rv32im/elfs/rv32i/I/I-addi-00.elf
  - sw/arch-tests/riscv-arch-test/work/ama-riscv-rv32im/elfs/rv32i/I/I-lb-00.elf
  - sw/arch-tests/riscv-arch-test/work/ama-riscv-rv32im/elfs/rv32i/I/I-fence-00.elf
  - sw/arch-tests/riscv-arch-test/work/ama-riscv-rv32im/elfs/rv32i/I/I-sra-00.elf
  - sw/arch-tests/riscv-arch-test/work/ama-riscv-rv32im/elfs/rv32i/I/I-sh-00.elf
  - sw/arch-tests/riscv-arch-test/work/ama-riscv-rv32im/elfs/rv32i/I/I-bltu-00.elf
  - sw/arch-tests/riscv-arch-test/work/ama-riscv-rv32im/elfs/rv32i/I/I-or-00.elf
  - sw/arch-tests/riscv-arch-test/work/ama-riscv-rv32im/elfs/rv32i/I/I-xor-00.elf
  - sw/arch-tests/riscv-arch-test/work/ama-riscv-rv32im/elfs/rv32i/I/I-sltiu-00.elf
  - sw/arch-tests/riscv-arch-test/work/ama-riscv-rv32im/elfs/rv32i/I/I-slt-00.elf
  - sw/arch-tests/riscv-arch-test/work/ama-riscv-rv32im/elfs/rv32i/I/I-srl-00.elf
  - sw/arch-tests/riscv-arch-test/work/ama-riscv-rv32im/elfs/rv32i/I/I-ori-00.elf
  - sw/arch-tests/riscv-arch-test/work/ama-riscv-rv32im/elfs/rv32i/I/I-beq-00.elf
  - sw/arch-tests/riscv-arch-test/work/ama-riscv-rv32im/elfs/rv32i/I/I-sb-00.elf
  - sw/arch-tests/riscv-arch-test/work/ama-riscv-rv32im/elfs/rv32i/I/I-srli-00.elf
  - sw/arch-tests/riscv-arch-test/work/ama-riscv-rv32im/elfs/rv32i/I/I-auipc-00.elf
  - sw/arch-tests/riscv-arch-test/work/ama-riscv-rv32im/elfs/rv32i/I/I-slti-00.elf
  - sw/arch-tests/riscv-arch-test/work/ama-riscv-rv32im/elfs/rv32i/I/I-add-00.elf
  - sw/arch-tests/riscv-arch-test/work/ama-riscv-rv32im/elfs/rv32i/I/I-sltu-00.elf

  - sw/arch-tests/riscv-arch-test/work/ama-riscv-rv32im/elfs/rv32i/M/M-mulhsu-00.elf
  - sw/arch-tests/riscv-arch-test/work/ama-riscv-rv32im/elfs/rv32i/M/M-rem-00.elf
  - sw/arch-tests/riscv-arch-test/work/ama-riscv-rv32im/elfs/rv32i/M/M-div-00.elf
  - sw/arch-tests/riscv-arch-test/work/ama-riscv-rv32im/elfs/rv32i/M/M-mulh-00.elf
  - sw/arch-tests/riscv-arch-test/work/ama-riscv-rv32im/elfs/rv32i/M/M-remu-00.elf
  - sw/arch-tests/riscv-arch-test/work/ama-riscv-rv32im/elfs/rv32i/M/M-divu-00.elf
  - sw/arch-tests/riscv-arch-test/work/ama-riscv-rv32im/elfs/rv32i/M/M-mulhu-00.elf
  - sw/arch-tests/riscv-arch-test/work/ama-riscv-rv32im/elfs/rv32i/M/M-mul-00.elf

  - sw/arch-tests/riscv-arch-test/work/ama-riscv-rv32imc/elfs/rv32i/Zbb/Zbb-max-00.elf
  - sw/arch-tests/riscv-arch-test/work/ama-riscv-rv32imc/elfs/rv32i/Zbb/Zbb-maxu-00.elf
  - sw/arch-tests/riscv-arch-test/work/ama-riscv-rv32imc/elfs/rv32i/Zbb/Zbb-min-00.elf
  - sw/arch-tests/riscv-arch-test/work/ama-riscv-rv32imc/elfs/rv32i/Zbb/Zbb-minu-00.elf

  - sw/arch-tests/riscv-arch-test/work/ama-riscv-rv32im/elfs/rv32i/Zicsr/Zicsr-csrrci-00.elf
  - sw/arch-tests/riscv-arch-test/work/ama-riscv-rv32im/elfs/rv32i/Zicsr/Zicsr-csrrwi-00.elf
  - sw/arch-tests/riscv-arch-test/work/ama-riscv-rv32im/elfs/rv32i/Zicsr/Zicsr-csrrs-00.elf
  - sw/arch-tests/riscv-arch-test/work/ama-riscv-rv32im/elfs/rv32i/Zicsr/Zicsr-csrrsi-00.elf
  - sw/arch-tests/riscv-arch-test/work/ama-riscv-rv32im/elfs/rv32i/Zicsr/Zicsr-csrrw-00.elf
  - sw/arch-tests/riscv-arch-test/work/ama-riscv-rv32im/elfs/rv32i/Zicsr/Zicsr-csrrc-00.elf

  - sw/arch-tests/riscv-arch-test/work/ama-riscv-rv32im/elfs/rv32i/Zicntr/Zicntr-csrrs-00.elf
  - sw/arch-tests/riscv-arch-test/work/ama-riscv-rv32im/elfs/rv32i/Zicntr/Zicntr-csrrc-00.elf

  - sw/arch-tests/riscv-arch-test/work/ama-riscv-rv32im/elfs/rv32i/Zihpm/Zihpm-csrrc-00.elf
  - sw/arch-tests/riscv-arch-test/work/ama-riscv-rv32im/elfs/rv32i/Zihpm/Zihpm-csrrs-00.elf
